### ISSUE TITLE
ViewChild instance of NgMapsViewComponent is undefined

### ISSUE THREAD

**Issue by piyushgoyal25** [ng-maps/ng-maps#108]
I am trying to access NgMapsViewComponent via ViewChild in my app and the instance always comes as undefined.

`@ViewChild(NgMapsViewComponent) public ngMap: NgMapsViewComponent<any>;

this.ngMap.triggerResize();
`

Uncaught TypeError: Cannot read properties of undefined (reading 'triggerResize')

**Comment by DaSchTour** [comment]
When using google maps you probably have to use GoogleComponent as it extends the NgMapsViewComponent and is used as the wrapper in google context.

**Comment by piyushgoyal25** [comment]
> When using google maps you probably have to use GoogleComponent as it extends the NgMapsViewComponent and is used as the wrapper in google context.

Thank you. That worked.
