### ISSUE TITLE
Angular compatibility

### ISSUE THREAD

**Issue by KQuiskamp** [ng-maps/ng-maps#146]
I have run some test in older projects with angular 15.x. 

The newest @ng-maps/core@5.0.1 and @ng-maps/google@5.0.2 package do not work here. In angular project 16.x all packages works fine. 

The error look like a typescript error after building with ng-packagr.  [16.0.0](https://github.com/ng-packagr/ng-packagr/releases/tag/16.0.0) the typescript 4.8 used in angular 15.x is deprecated.

I guess we must use [15.2.2](https://github.com/ng-packagr/ng-packagr/releases/tag/15.2.2) for compiling angular 15.x versions.

Maybe we should use the major version for the angular version in our packages and the minor for adding new features.

So our versions always equals the angular versions for better understanding.

![image](https://github.com/ng-maps/ng-maps/assets/6818495/02aa5696-5384-4942-9496-a3557e025e01)

**Comment by DaSchTour** [comment]
If there is the need for a version that is compatible with angular 15 I would see if we can port changes to the older 4 version.

**Comment by rushvora** [comment]
I ended up adding `skipLibCheck: true` to fix this issue for an Angular 15 based application.
