### ISSUE TITLE
Angular 17 compatibily

### ISSUE THREAD

**Issue by Juliete** [ng-maps/ng-maps#171]
Is planned to provide Angular 17+ compatibility?

**Comment by DaSchTour** [comment]
@Juliete yes it is planned

**Comment by shajz** [comment]
Hi @DaSchTour, it's been a few months, how is the ng 17 upgrade going? Do you need any help?

**Comment by DaSchTour** [comment]
@shajz help is always appreciated, that's why this project started with an organization, the update to angular 17 is on the way
