### ISSUE TITLE
Docs/Readme have incorrect import instructions

### ISSUE THREAD

**Issue by warmans** [ng-maps/ng-maps#62]
The docs suggest importing the core module with a `forRoot()` call to pass the apiKey. But the sample application passes the key through a provider (and indeed forRoot is not applicable to the exported core module). Additionally it's not clear that to use google maps the google module must also be imported.

**Comment by jfan0888** [comment]
@DaSchTour 
From the documentation, it suggest to add apiKey in forRoot() `NgMapsCoreModule.forRoot()`
but I can't use forRoot() in app.module.ts

**Comment by warmans** [comment]
The sample application show the correct way to import the module: 

https://github.com/ng-maps/ng-maps/blob/master/projects/sample/src/app/app.module.ts#L25

**Comment by DaSchTour** [comment]
I updated the docs. Thanks
