### ISSUE TITLE
Autocomplete errors

### ISSUE THREAD

**Issue by calvinturbo** [ng-maps/ng-maps#69]
I have migrated from agm-maps to your project. Thanks for updating the code.

Unfortunately, my Google Maps Autocomplete seems to have stopped working.

> core.mjs:7644 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'Autocomplete')
> TypeError: Cannot read properties of undefined (reading 'Autocomplete')

I import 'NgMapsPlacesModule' in app.module.ts

`@NgModule({
  imports: [
    NgMapsCoreModule,
    NgMapsGoogleModule,
    NgMapsPlacesModule,
    NgMapsMarkerClustererModule,
    BrowserModule,`

and in a shared module

`@NgModule({
  imports: [
    NgMapsCoreModule,
    NgMapsGoogleModule,
    NgMapsMarkerClustererModule,
    NgMapsPlacesModule,`

My TS component code (simplified), code is being called from ngViewAfterInit:
` // load Places Autocomplete
    this.mapsAPILoader.load().then(() => {
      this.geocoder = new google.maps.Geocoder();
      const autocomplete = new google.maps.places.Autocomplete(this.searchElementRef.nativeElement);
      autocomplete.addListener('place_changed', () => {
        this.ngZone.run(() => {
          // get the place result
          const place: google.maps.places.PlaceResult = autocomplete.getPlace();
`

TS component constructor:

```
constructor(
    public dialogRef: MatDialogRef<DialogAddressLookupGoogleComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any, public definedInfo: DefinedInfo,
    private mapsAPILoader: MapsAPILoader,
    private ngZone: NgZone,
    private filterService: FilterService,
    private addressService: AddressService,
    public translate: TranslateService,
    public _snackbar: MatSnackBar,
    public permissionService: PermissionService) {

  }
```

and imported from 
import {MapsAPILoader} from '@ng-maps/core';

Why is not working? It seems that new google.maps.places does not exist, indicating that NgMapsPlacesModule hasn't successfully been loaded in.

**Comment by DaSchTour** [comment]
Did you try to add the following?
```
NgMapsCoreModule.forRoot({
  libraries: ['places'],
});
```
As stated in the documentation: https://ng-maps.github.io/places/index.html

**Comment by calvinturbo** [comment]
The documentation is unfortunately incorrect, NgMapsCoreModule doesn't have forRoot, Intellji gives an error when I put that in my code.

**Comment by DaSchTour** [comment]
Oh yes, your are right. I'm sorry. I changed this in one of the recent version and didn't adjust the documentation. The configuration was moved to the provider, you also use for adding the API key.

```
{
  provide: GOOGLE_MAPS_API_CONFIG,
  useValue: {
    …
    libraries: ['places']
  }
}
```

**Comment by calvinturbo** [comment]
Thanks, that solves the issue, autocomplete works again :)
