### ISSUE TITLE
Google Maps Types moved to different NPM package (conflict between old and new)

### ISSUE THREAD

**Issue by geferon** [ng-maps/ng-maps#72]
The Google maps types have moved to [@types/google.maps](https://www.npmjs.com/package/@types/google.maps), [@types/googlemaps](https://www.npmjs.com/package/@types/googlemaps) being deprecated.
The package included by @ng-maps/marker-clusterer includes @types/markerclustererplus (as seen in https://github.com/ng-maps/ng-maps/blob/c52a04fa2b45778625f07f3203d702f99b2bfc82/libs/marker-clusterer/package.json#L23 ) which has @types/google-maps as a dependency, which at the same time has @types/google.maps as a dependency itself.

This makes it so whenever both packages are installed, and you try to compile, @types/googlemaps and @types/google.maps conflict with each other.
The solution would be to update the typings in the @ng-maps/marker-clusterer library from @google/markerclusterer to @googlemaps/markerclusterer
https://github.com/ng-maps/ng-maps/blob/c52a04fa2b45778625f07f3203d702f99b2bfc82/libs/marker-clusterer/package.json#L22
and swap @types/markerclustererplus for @types/google.maps, as in the new versions the markerclusterer is included in it.

**Comment by ivan-lemon** [comment]
I encountered the same issue. Has there been a fix for this or a workaround?

**Comment by DaSchTour** [comment]
New version 4 is released with updates for angular and google maps typings
