### ISSUE TITLE
Angular 14 - Autocomplete issue

### ISSUE THREAD

**Issue by phenric** [ng-maps/ng-maps#73]
I've this issue using the autocomplete

`main.js:1 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(n)[Z_ -> Z_ -> Z_]: 
  NullInjectorError: No provider for Z_!
NullInjectorError: R3InjectorError(n)[Z_ -> Z_ -> Z_]: 
  NullInjectorError: No provider for Z_!`

I saw on the web it could be due to Angular 14. Do you face the same with NG14?

I declared it as described in the providers in app.module
`{
          provide: GOOGLE_MAPS_API_CONFIG,
          useValue: {
            apiKey: environment.AGMAPS_API,
            libraries: ['places']
          }
        }`

and I can see the map but when I add the input autocomplete, it crashes.

**Comment by phenric** [comment]
Hi @DaSchTour I'm not able to create a new branch. Can you give me the right?

**Comment by DaSchTour** [comment]
@phenric you can create a fork, create a branch there and then create a pull-request. That's the procedure I normally use and see in other repos.

**Comment by phenric** [comment]
Hi @DaSchTour Thanks for the reply.

I made the pull request #74 
Let me know if you agree with my suggestion :)

**Comment by DaSchTour** [comment]
Fixed in 3.0.1
