### ISSUE TITLE
ng-maps not able to install on latest Angular 14.2

### ISSUE THREAD

**Issue by kellySmi** [ng-maps/ng-maps#75]
I created a new Angular project from the command line  `ng new projectName` 
I then tried to install @ng-maps `npm i @ng-maps-core` 
I receive peer dependency errors:
`Conflicting peer dependency: @angular/platform-browser-dynamic@14.2.0
npm ERR! node_modules/@angular/platform-browser-dynamic
npm ERR!   peer @angular/platform-browser-dynamic@"14.2.0" from @ng-maps/core@3.0.2
npm ERR!   node_modules/@ng-maps/core
npm ERR!     @ng-maps/core@"*" from the root project`
 I have tried downgrading the Angular version and the @ng-maps but have not found the combination that will allow an install without forcing it or using the legacy-peer-deps flag.
 I have also tried removing the node_modules and package-lock file and reinstalling without success.

**Comment by longwa** [comment]
Not sure why the dependencies in @ng-maps/core are locked to a specific version of Angular 14.2.0. Seems like it would be better to build with "^14.2.0" instead to allow for minor and patch versions right?

**Comment by DaSchTour** [comment]
New version 4 is released with updates for angular and google maps typings
